const ROLES = {
    "Admin": 1,
    "Security-Analyst": 2,
    "Responder": 3,
    "Auditor": 4
}

const GET_ALL_VULNERABILITIES_VALID_ROLES = [1]

const ADD_NEW_VULNERABILITIES_VALID_ROLES = [1,2]

const ASSIGN_VULNERABILITIES_VALID_ROLES = [1,2]

const UPDATE_VULNERABILITIES_STATUS_VALID_ROLES = [1,2,3]

const VIEW_RESOLVED_VULNERABILITIES_VALID_ROLES = [1,2,3,4]

export { 
    ROLES,
    GET_ALL_VULNERABILITIES_VALID_ROLES,
    ADD_NEW_VULNERABILITIES_VALID_ROLES,
    ASSIGN_VULNERABILITIES_VALID_ROLES, 
    UPDATE_VULNERABILITIES_STATUS_VALID_ROLES,
    VIEW_RESOLVED_VULNERABILITIES_VALID_ROLES,
}